Draft oneway
Linutronix/TSN-Testbench pull request #8
Opened 2024-06-28 07:29 UTC by wtedeschi

Hi Kurt,

Here we have two bug fixes and 2 new functionalities:
1. Log is enabled also on the mirror side
2. Oneway latency is included with the logging.

For one way i have tested also the AO and AE security, both worked with the current code.

Thanks,
/Fred

2024-06-28 14:17 UTC, shifty91 requested changes
Hi Fred,

nice work. Can you address the following overall issues? Then, I'll merge it.

- Adjust the Tx time stamp on `mirror` side (to make one way measurements symmetrical)
- Run `clang-format`
- Fix build errors and warnings
- Stick to RCT

2024-06-28 14:17 UTC, shifty91 commented on src/dcp_thread.c
> +	struct timespec tx_time = {};
Please, stick to RCT for variable ordering. Here and everywhere else.

See https://docs.kernel.org/process/maintainer-netdev.html#local-variable-ordering-reverse-xmas-tree-rcs

2024-06-28 14:17 UTC, shifty91 commented on src/dcp_thread.c
> +	tx_timestamp_to_meta_data(&rt->meta_data, ts_to_ns(&tx_timespec_mirror));
Here the original frame is modified. There's a function for building the mirror'ed frames: `dcp_build_frame_from_rx().` Ideally move it to that function.

Furthermore, the timestamp `tx_timespec_mirror` is not really the tx timestamp. It needs to be adjusted by the delay between Rx and Tx.

Applies to all the other traffic classes as well.

2024-06-28 14:17 UTC, shifty91 commented on src/layer2_thread.c
> +
Spurious new line.

2024-06-28 14:17 UTC, shifty91 commented on src/rta_thread.c
> +
Spurious new lines.

2024-06-28 14:17 UTC, shifty91 commented on src/rta_thread.c
> +		        begin_of_security_checksum);
The indentation is wrong here. Use `clang-format` to get it fixed automatically.

2024-06-28 14:17 UTC, shifty91 commented on src/rtc_thread.c
> +		frame_config.tx_timestamp = ts_to_ns(&tx_time);
This `tx_time` is always zero. It misses the call to `clock_gettime()`

2024-06-28 14:17 UTC, shifty91 commented on src/stat.c
> +		stat->oneway_outliers++;
Nice, outliers are detected. However, they're not logged.

2024-06-28 16:27 UTC, wtedeschi commented
Hi Kurt,

Thanks for the quick review!
I have addressed all the comments, I will be testing by Monday and submitting an update.

Best regards,
/Fred

2024-07-02 11:37 UTC, closed without merging

2024-07-02 11:38 UTC, shifty91 commented
@wtedeschi Applied, thank you.